Fix for race condition with brew bundle install

diff --git a/.github/workflows/validate-brewfiles.yml b/.github/workflows/validate-brewfiles.yml
--- a/.github/workflows/validate-brewfiles.yml
+++ b/.github/workflows/validate-brewfiles.yml
@@ -24,12 +24,13 @@ jobs:
           find "custom/brew" -iname '*\.Brewfile*' -print0 | \
             while IFS= read -r -d '' brewfile ; do
               echo "::group:: ===$(basename "$brewfile")==="
-              brew bundle --file="$brewfile" 
-              if brew bundle check --file="$brewfile" 2>&1; then
-                echo "✓ $brewfile is valid"
-              else
-                echo "✗ $brewfile validation failed"
-                exit 1
+              if brew bundle --file="$brewfile" ; then
+                if brew bundle check --file="$brewfile" 2>&1; then
+                  echo "✓ $brewfile is valid"
+                else
+                  echo "✗ $brewfile validation failed"
+                  exit 1
+                fi
               fi
               echo "::endgroup::"
             done
