Another attempt to fix brew bundle install error

diff --git a/.github/workflows/validate-brewfiles.yml b/.github/workflows/validate-brewfiles.yml
--- a/.github/workflows/validate-brewfiles.yml
+++ b/.github/workflows/validate-brewfiles.yml
@@ -24,13 +24,14 @@ jobs:
           find "custom/brew" -iname '*\.Brewfile*' -print0 | \
             while IFS= read -r -d '' brewfile ; do
               echo "::group:: ===$(basename "$brewfile")==="
-              if brew bundle --file="$brewfile" ; then
-                if brew bundle check --file="$brewfile" 2>&1; then
-                  echo "✓ $brewfile is valid"
-                else
-                  echo "✗ $brewfile validation failed"
-                  exit 1
-                fi
+              if ![brew bundle --file="$brewfile"] ; then
+                echo "✗ $brewfile installation failed"
+              fi
+              if brew bundle check --file="$brewfile" 2>&1; then
+                echo "✓ $brewfile is valid"
+              else
+                echo "✗ $brewfile validation failed"
+                exit 1
               fi
               echo "::endgroup::"
             done
